# Generated by Django 4.2.5 on 2023-09-21 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='pet',
            name='interests',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='pet',
            name='location',
            field=models.CharField(default='Unknown Location', max_length=100),
        ),
        migrations.AddField(
            model_name='pet',
            name='personality_traits',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(default='Unknown Name', max_length=100),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='No comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pets.pet')),
            ],
        ),
    ]
