# Generated by Django 4.2.5 on 2023-09-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_tag_remove_comment_comment_remove_comment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='tags',
            field=models.ManyToManyField(related_name='pets', through='pets.Pet_Tag', to='pets.tag'),
        ),
    ]
